name: 'build-test'
on:
  push

jobs:
  build-and-liveness-check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '21'
      - shell: bash
        run: cd examples && ./docker-build.sh test
      - run: cd examples && docker compose --verbose up --build --wait
